export const PERMISSIONS = {
	STORE_CONFIGURE: "store.configure",
	EMPLOYEES_MANAGE: "employees.manage",
	CATEGORIES_MANAGE: "categories.manage",
	PRODUCTS_CREATE_PUBLISH: "products.create_publish",
	PRODUCTS_EDIT_PUBLISHED: "products.edit_published",
	PRODUCTS_ARCHIVE: "products.archive",
	PRODUCTS_SET_PRICE: "products.set_price",
	SALES_RECORD: "sales.record",
	CUSTOMERS_MANAGE: "customers.manage",
	INVOICES_RECORD_PAYMENT: "invoices.record_payment",
	STOCK_VIEW: "stock.view",
	SUPPLIERS_MANAGE: "suppliers.manage",
	PURCHASE_ORDERS_CREATE: "purchase_orders.create",
	PURCHASE_ORDERS_VIEW: "purchase_orders.view",
	DELIVERIES_SIGN_OFF: "deliveries.sign_off",
	SUPPLIERS_RECORD_PAYMENT: "suppliers.record_payment",
	EXPENSES_MANAGE: "expenses.manage",
	REPORTS_VIEW: "reports.view",
	ANALYTICS_VIEW: "analytics.view",
	DELIVERIES_CONFIRM_DISCREPANCY: "deliveries.confirm_discrepancy",
	INVENTORY_ADJUST: "inventory.adjust",
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const ROLES = [
	"admin",
	"manager",
	"sales_clerk",
	"inventory_clerk",
	"accountant",
] as const;

export type Role = (typeof ROLES)[number];

const ALL_PERMISSIONS: readonly Permission[] = Object.values(PERMISSIONS);

export const ROLE_PERMISSIONS = {
	admin: ALL_PERMISSIONS,
	manager: [
		PERMISSIONS.EMPLOYEES_MANAGE,
		PERMISSIONS.CATEGORIES_MANAGE,
		PERMISSIONS.PRODUCTS_CREATE_PUBLISH,
		PERMISSIONS.PRODUCTS_EDIT_PUBLISHED,
		PERMISSIONS.PRODUCTS_ARCHIVE,
		PERMISSIONS.PRODUCTS_SET_PRICE,
		PERMISSIONS.SALES_RECORD,
		PERMISSIONS.CUSTOMERS_MANAGE,
		PERMISSIONS.INVOICES_RECORD_PAYMENT,
		PERMISSIONS.STOCK_VIEW,
		PERMISSIONS.SUPPLIERS_MANAGE,
		PERMISSIONS.PURCHASE_ORDERS_CREATE,
		PERMISSIONS.PURCHASE_ORDERS_VIEW,
		PERMISSIONS.DELIVERIES_SIGN_OFF,
		PERMISSIONS.SUPPLIERS_RECORD_PAYMENT,
		PERMISSIONS.EXPENSES_MANAGE,
		PERMISSIONS.REPORTS_VIEW,
		PERMISSIONS.ANALYTICS_VIEW,
		PERMISSIONS.DELIVERIES_CONFIRM_DISCREPANCY,
		PERMISSIONS.INVENTORY_ADJUST,
	],
	sales_clerk: [
		PERMISSIONS.SALES_RECORD,
		PERMISSIONS.CUSTOMERS_MANAGE,
		PERMISSIONS.INVOICES_RECORD_PAYMENT,
		PERMISSIONS.STOCK_VIEW,
	],
	inventory_clerk: [
		PERMISSIONS.PRODUCTS_CREATE_PUBLISH,
		PERMISSIONS.STOCK_VIEW,
		PERMISSIONS.PURCHASE_ORDERS_VIEW,
		PERMISSIONS.DELIVERIES_SIGN_OFF,
	],
	accountant: [
		PERMISSIONS.INVOICES_RECORD_PAYMENT,
		PERMISSIONS.EXPENSES_MANAGE,
		PERMISSIONS.REPORTS_VIEW,
	],
} as const satisfies Record<Role, readonly Permission[]>;
